### ISSUE TITLE
Cannot manipulate 'rfm_results' tibble

### ISSUE THREAD

**Issue by Yvanyvanyvan** [rsquaredacademy/rfm#15]
Hello! Exploring your package and want to assign segments depending on scores (as you show in the article on website). 

While trying to do anything with rfm_result get this error

`> rfm_result_summary<-select(rfm_result,rfm_score)
Error in .f(.x[[i]], ...) : object 'rfm_score' not found`

Conversion to df also does not seem to work

`rfm_result_summary<-as_data_frame(rfm_result)
Error: Column `rfm` must be a 1d atomic vector or a list`

PS Sorry if I am missing something, as I am new to programming.

**Comment by aravindhebbali** [comment]
You can access the RFM table using `rfm_result$rfm` and the `rfm_score` column using `rfm_result$rfm$rfm_score`. I have modified your code below:

```
library(magrittr)
rfm_result_summary <-
  rfm_result %>%
  use_series(rfm) %>% 
  select(rfm_score)
```

Let me know if the above code works.

**Comment by Yvanyvanyvan** [comment]
Works great, many thanks! 

BTW do you plan to add functionality for easy segmentation to "pre-default' customer segments within the package?

**Comment by aravindhebbali** [comment]
Correct me if I am wrong.. by pre-default, do you mean that the package should create the segmentation based on the RFM score? Since the criteria for segmentation is very subjective and based on the number of bins used for recency, frequency & monetary score, I thought it would be best if left to the end user to decide on the criteria for segmentation. Let me know if you have any suggestions.

**Comment by Yvanyvanyvan** [comment]
Basic scoring is fairly unified (I.e. "at risk", "hibernating", etc). I would suggest to introduce simple function to segment by ranges like you specified in you guide on side. And users could add specific scores as separate arguments/function.
